model:
  name: rf
  save_dir: rf
  space:
    n_estimators:
      type: quniform
      low: 100
      high: 1000
      step: 50
      int: true
    max_depth:
      type: quniform
      low: 3
      high: 20
      step: 1
      int: true
    min_samples_split:
      type: quniform
      low: 2
      high: 10
      step: 1
      int: true
    random_state:
      type: quniform
      low: 1
      high: 100
      step: 1
      int: true
data:
  dataset_name: titanic
  raw_data_path: data/raw
  processed_data_path: data/processed
  file_name: train
  id_col: PassengerId
  target_col: Survived
  test_size: 0.15
  random_state: 42
tuning:
  n_folds: 5
  max_evals: 10
  scoring: accuracy
paths:
  model_path: models/
  translator_path: models/rf/model_target_translator.pkl
  reports_path: reports
  preprocessor_path: models/preprocessor.pkl
experiment_name: my_experiment
