defaults:
  - model: lr
  - data: titanic
  - tuning: hyperopt
  - _self_

paths:
  model_path: models/
  translator_path: models/fake/model_target_translator.pkl
  reports_path: reports

experiment_name: my_experiment